openapi: 3.0.0
info:
  title: 'Alaya Blog API'
  description: 'Alaya Blog API'
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:3000'
paths:
  /signup:
    post:
      summary: Signup
      description: Signup
      operationId: signup

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Error on signup
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      summary: Log in
      description: Log in
      operationId: login

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User created
        '400':
          description: Error on log in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /posts:
    get:
      summary: Get all posts
      description: Get all posts
      operationId: getPosts

      responses:
        '200':
          description: All posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
                    name:
                      type: string
                    author:
                      type: string
    post:
      summary: Create a post
      description: Create a post
      operationId: createPost

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: Post created
  /posts/{title}:
    parameters:
      - name: title
        in: path
        required: true
        description: The post title
        schema:
          type:
            string
    get:
      summary: Get a post
      description: Get a post
      operationId: getPost

      responses:
        '200':
          description: A post
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  content:
                    type: string
                  name:
                    type: string
    delete:
      summary: Delete a post
      description: Delete a post
      operationId: deletePost

      responses:
        '200':
          description: Post deleted